# Feature toggles
use_plm: true
use_gemme: false
use_ddg_foldx: true
use_ddg_rosetta: false
use_deepddg: false
use_disorder: true
use_priors: true

# Hardware acceleration (GPU available: NVIDIA GeForce RTX 3050)
device: cuda

# Priors configuration
priors_yaml: data/priors/priors_petase_2024_2025.yaml

# FoldX configuration
foldx_exe: tools/foldx/foldx_wsl.bat
foldx_pdb: tools/foldx/5XJH.pdb
foldx_chain: A
foldx_timeout: 300

# Ensemble weights
weights:
  activity:
    plm_llr: 0.55
    gemme: 0.25
    priors: 0.20
  stability:
    ddg_foldx: 0.35
    ddg_rosetta: 0.00
    ddg_deepddg: 0.00
    plm_perplexity: 0.10
    priors: 0.15
  expression:
    solubility_proxy: 0.70
    disorder_proxy: 0.30
